seed: 0
exp_name:

device:
  cuda_device: cuda:0
  gpu_num_workers: 32

data:
  dataset_name: CLARO_R

  img_dir: /Volumes/T7/CLARO DATA/Polmoni retrospettivi (125pz)/Immagini/share/Polmoni retrospettivi (125pz)/Immagini
  interim_dir: /Volumes/T7/data/interim/
  processed_dir: /Volumes/T7/data/processed/
  info_file: /Volumes/T7/data/interim/CLARO_P/patients_info.xlsx
  label_file: /Volumes/T7/CLARO DATA/Polmoni retrospettivi (125pz)/-per_estrazione-/Dati clinici (130pz - da escludere gli scartati).xls
  metadata_file: False

  classes:
    "adaptive": 1
    "non-adaptive": 2
  preprocessing:
    # resize
    img_size: 256
    interpolation: linear
    # normalization and clip
    range:
      min: -1000 # -1200 # -1000
      max: 1000 # 400 # 1000
    upper_percentile:
    lower_percentile:
    to_255:
    file_format: .tiff # .pkl
  dicom_tags:
    - PatientID
    - PatientName
    - SliceThickness
    - RescaleIntercept
    - RescaleSlope
    - PixelSpacing
    - BitsAllocated
    - BitsStored
    - PixelRepresentation
    - ImageOrientationPatient
    - ImagePositionPatient
    - ImageType
    - Manufacturer
    - ManufacturerModelName
    - PhotometricInterpretation
    - WindowCenter
    - WindowWidth
